{% set name = "inotify_simple" %}
{% set version = "1.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 73d767b3b1e943cf54351160e8e5339ca7f0e08c38ad09d0435c6a80c4cd800a

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [win]

requirements:
  host:
    - pip
    - python
    - enum34  # [py<34]
  run:
    - python
    - enum34  # [py<34]
test:
  requires:
    - enum34  # [py<34]
  imports:
    - inotify_simple

about:
  home: https://github.com/chrisjbillington/inotify_simple
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A simple wrapper around inotify. No fancy bells and whistles, just a literal wrapper with ctypes. Only 127 lines of code!
  doc_url: https://pypi.org/project/inotify_simple/
  dev_url: https://github.com/chrisjbillington/inotify_simple

extra:
  recipe-maintainers:
    - mwilson8
    - rluria14
    - benhuff
