{% set name = "inotify_simple" %}
{% set version = "1.3.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8440ffe49c4ae81a8df57c1ae1eb4b6bfa7acb830099bfb3e305b383005cc128

build:
  number: 2
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - pip
    - python
    - enum34  # [py<34]
  run:
    - python
    - enum34  # [py<34]
test:
  requires:
    - enum34  # [py<34]
  imports:
    - inotify_simple

about:
  home: https://github.com/chrisjbillington/inotify_simple
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A simple wrapper around inotify. No fancy bells and whistles, just a literal wrapper with ctypes. Only 127 lines of code!
  doc_url: https://pypi.org/project/inotify_simple/
  dev_url: https://github.com/chrisjbillington/inotify_simple

extra:
  recipe-maintainers:
    - mwilson8
    - rluria14
    - benhuff
